language: 
  - python
  - cpp

python:
- '3.6'

before_install:
  - |
    mkdir -p ~/tmp
    wget -P ~/tmp https://github.com/Kitware/CMake/releases/download/v3.15.0-rc3/cmake-3.15.0-rc3.tar.gz
    tar -xzf ~/tmp/cmake-3.15.0-rc3.tar.gz -C ~/tmp
    cmake ~/tmp/cmake-3.15.0-rc3 -B~/tmp/cmake-3.15.0-rc3
    make -C ~/tmp/cmake-3.15.0-rc3
    sudo make install -C ~/tmp/cmake-3.15.0-rc3
install:
- pip install -r dev-requirements.txt
- pip install --upgrade pip

script:
- pytest tests/ -v
- pycodestyle gaia_image_processing/*

after_script:
- py.test --cov-report term --cov=. --ignore=tests/* --cov-report=html
- coverage xml
- python-codacy-coverage -r coverage.xml

notification:
  email: false

before_deploy:
  - echo 'Beggining deploy...'
  - python3 setup.py build
  - python3 setup.py sdist bdist_wheel

deploy:
  - provider: script
    script: bash deploy.sh deploy
    on:
      branch: master
